# Generated by Django 5.1.1 on 2024-10-04 23:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=9)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=9)),
                ('criadoEm', models.DateTimeField(auto_now_add=True)),
                ('telefone_celular', models.CharField(max_length=14)),
                ('telefone_fixo', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
