# Generated by Django 5.1.2 on 2024-10-11 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_funcionario_escolaridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone_celular',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone celular deve estar no formato (99)99999-9999', regex='^\\(\\d{2}\\)\\s?\\d{5}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone_celular',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone celular deve estar no formato (99)99999-9999', regex='^\\(\\d{2}\\)\\s?\\d{5}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone_celular',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone celular deve estar no formato (99)99999-9999', regex='^\\(\\d{2}\\)\\s?\\d{5}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone_celular',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone celular deve estar no formato (99)99999-9999', regex='^\\(\\d{2}\\)\\s?\\d{5}-\\d{4}$')]),
        ),
    ]
